import Head from 'next/head'
import ApercuPro from 'next/font/local'

const apercuPro = ApercuPro({
  src: './fonts/apercu_pro.otf'
})

export default function ChallengesPage() {
  return (
    <>
      <Head>
        <title>Blooming 🌸</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={apercuPro.className}>
        <h2>challenges</h2>
      </main>
    </>
  )
}
